##=== Calbuco
#year = 2015
#doys = [112] # April 22, day of eruption
#sec = 75600 # 21:00 UTC, ~start of eruption
#=== PCCVC
year = 2011
doys = [155] # June 4, day of eruption
sec = 68400 # 19:00 UTC, ~start of eruption

hmin = 0.0 # km
hmax = 170.0 # km
dh = 0.5 # km

f107a = 150 # moderate solar activity
f107 = 150
apd = 4 # quiet geomagnetic activity
aph = 4


sou_pos = [
#    [-41.33, -72.62], # Calbuco
    [-40.59, -72.117] # PCCVC
]

sta_pos = [
    [-54.58057  , -67.30923], #I02AR
    [-16.21523  , -68.45345], #I08BO
    [-15.637967 , -48.016422], #I09BR
    [-27.12726  , -109.36265], #I13CL
    [-33.65379  , -78.79598], #I14CL
    [-70.7011   , -8.30291], #I27DE
    [-26.34230  , -57.31188], #I41PY
    [-37.08995  , -12.33192] #I49GB
]

sta_nam = [ 
    "IS02",
    "IS08",
    "IS09",
    "IS13",
    "IS14",
    "IS27",
    "IS41",
    "IS49"
]

sta_skp = [
    3, # IS13
#    2, # IS14
    ]

ds = 50.0 # km

# If using RngDep
[range_dependent]
use_rng_dep = false
dlat = 3.0
dlon = 3.0

[ecmwf]
use_ecmwf = true
auto_area = true
min_lon = -110 # to define area for grid
max_lon = -10
min_lat = -80
max_lat = 0
dlon = 1.0  # grid step in degrees
dlat = 1.0
h1 = 60.0 # km, heights to start and end merge
h2 = 80.0
